/**
 * Provider catalog — single source of truth for the API Keys tab dropdown
 * and the env-var → provider mapping that powers seed-import + masking.
 *
 * Bootstrap secrets (Supabase, ADMIN_PIN, SESSION_SIGNING_SECRET, CRON_SECRET,
 * OUTREACH_MEMORY_MCP_KEY) are intentionally absent — they must stay in
 * process.env or the secret-reader can't bootstrap itself.
 */

export type Category = "AI / LLM" | "Search & Scraping" | "Communication" | "Social" | "Infrastructure" | "Workflow & Storage" | "Other"

export type ProviderEntry = {
  slug: string
  label: string
  emoji?: string
  category?: Category
  envVars: string[] // canonical first
  help: string
  href?: string
  placeholder?: string
  testable?: boolean
}

export const CATEGORY_ORDER: Category[] = [
  "AI / LLM",
  "Search & Scraping",
  "Communication",
  "Social",
  "Infrastructure",
  "Workflow & Storage",
  "Other",
]

export const PROVIDERS: ProviderEntry[] = [
  {
    slug: "openai",
    category: "AI / LLM",
    label: "OpenAI",
    emoji: "🤖",
    envVars: ["OPENAI_API_KEY"],
    help: "Powers AI message generation and captions.",
    href: "https://platform.openai.com/api-keys",
    placeholder: "sk-...",
    testable: true,
  },
  {
    slug: "anthropic",
    category: "AI / LLM",
    label: "Anthropic Claude",
    emoji: "🧠",
    envVars: ["ANTHROPIC_API_KEY"],
    help: "Claude-powered writers and the in-app agent.",
    href: "https://console.anthropic.com/settings/keys",
    placeholder: "sk-ant-...",
    testable: true,
  },
  {
    slug: "apify",
    category: "Search & Scraping",
    label: "Apify",
    emoji: "🕸️",
    envVars: ["APIFY_TOKEN", "APIFY_API_TOKEN"],
    help: "Powers Social Scout scraping.",
    href: "https://console.apify.com/account/integrations",
    placeholder: "apify_api_...",
    testable: true,
  },
  {
    slug: "instantly",
    category: "Communication",
    label: "Instantly",
    emoji: "📧",
    envVars: ["INSTANTLY_API_KEY"],
    help: "Email outreach sender.",
    href: "https://app.instantly.ai/app/settings/integrations",
    placeholder: "Paste your Instantly API key",
    testable: true,
  },
  {
    slug: "ghl_key",
    category: "Communication",
    label: "GoHighLevel API Key",
    emoji: "📱",
    envVars: ["GHL_API_KEY"],
    help: "Send SMS via your GHL subaccount.",
    href: "https://help.gohighlevel.com/support/solutions/articles/48000982605",
    placeholder: "Bearer token from GHL → Settings → API Key",
    testable: true,
  },
  {
    slug: "ghl_sub",
    category: "Communication",
    label: "GHL Subaccount (Location) ID",
    emoji: "📍",
    envVars: ["GHL_SUBACCOUNT_ID", "GHL_LOCATION_ID"],
    help: "Location id under your agency that owns the SMS number.",
    placeholder: "abc123XYZsubaccountId",
  },
  {
    slug: "telegram_bot",
    category: "Communication",
    label: "Telegram Bot Token",
    emoji: "🤖",
    envVars: ["TELEGRAM_BOT_TOKEN"],
    help: "Bot token for Dead Man's Switch alerts. Create one with @BotFather.",
    placeholder: "123456:ABC-DEF...",
    testable: true,
  },
  {
    slug: "telegram_chat",
    category: "Communication",
    label: "Telegram Chat ID",
    emoji: "💬",
    envVars: ["TELEGRAM_CHAT_ID"],
    help: "Numeric chat id where alerts get sent. Get it from @userinfobot.",
    placeholder: "123456789",
    testable: true,
  },
  {
    slug: "telegram_webhook_secret",
    category: "Communication",
    label: "Telegram Webhook Secret",
    emoji: "🔒",
    envVars: ["TELEGRAM_WEBHOOK_SECRET"],
    help: "Random string Telegram echoes back in the X-Telegram-Bot-Api-Secret-Token header. Keeps random pokes at the webhook URL from running workflows. Generate any 32-char random string.",
    placeholder: "long-random-string-32-chars+",
  },
  {
    slug: "telegram_allowed_chats",
    category: "Communication",
    label: "Telegram Allowed Chat IDs",
    emoji: "👥",
    envVars: ["TELEGRAM_ALLOWED_CHAT_IDS"],
    help: "Comma-separated chat ids that may message Jarvis. Optional — TELEGRAM_CHAT_ID is always allowed. Use this to add a second device or a small group.",
    placeholder: "123456789,987654321",
  },
  {
    slug: "brave",
    category: "Search & Scraping",
    label: "Brave Search",
    emoji: "🔍",
    envVars: ["BRAVE_SEARCH_API_KEY", "BRAVE_API_KEY"],
    help: "Used by event scraping.",
    href: "https://brave.com/search/api/",
  },
  {
    slug: "elevenlabs",
    category: "AI / LLM",
    label: "ElevenLabs",
    emoji: "🎙️",
    envVars: ["ELEVENLABS_API_KEY"],
    help: "Text-to-speech / voice generation.",
    href: "https://elevenlabs.io/app/settings/api-keys",
  },
  {
    slug: "suno",
    category: "AI / LLM",
    label: "Suno",
    emoji: "🎵",
    envVars: ["SUNO_API_KEY"],
    help: "Music generation for video.",
  },
  {
    slug: "kling_access",
    category: "AI / LLM",
    label: "Kling Access Key",
    emoji: "🎬",
    envVars: ["KLING_ACCESS_KEY"],
    help: "Kling AI video generation (access key half).",
  },
  {
    slug: "kling_secret",
    category: "AI / LLM",
    label: "Kling Secret Key",
    emoji: "🎬",
    envVars: ["KLING_SECRET_KEY"],
    help: "Kling AI video generation (secret half).",
  },
  {
    slug: "kling_api",
    category: "AI / LLM",
    label: "Kling API Key",
    emoji: "🎬",
    envVars: ["KLING_API_KEY"],
    help: "Kling endpoint key (alternate flow).",
  },
  {
    slug: "google_oauth_id",
    category: "Communication",
    label: "Google OAuth Client ID",
    emoji: "🔑",
    envVars: ["GOOGLE_CLIENT_ID"],
    help: "OAuth client id for Gmail / Docs.",
    href: "https://console.cloud.google.com/apis/credentials",
  },
  {
    slug: "google_oauth_secret",
    category: "Communication",
    label: "Google OAuth Client Secret",
    emoji: "🔐",
    envVars: ["GOOGLE_CLIENT_SECRET"],
    help: "OAuth client secret for Gmail / Docs.",
  },
  {
    slug: "google_service_account",
    category: "Communication",
    label: "Google Service Account JSON",
    emoji: "📄",
    envVars: ["GOOGLE_SERVICE_ACCOUNT_JSON"],
    help: "Base64-encoded service-account JSON for Google Docs.",
  },
  {
    slug: "ms_oauth_id",
    category: "Communication",
    label: "Microsoft OAuth Client ID",
    emoji: "🔑",
    envVars: ["MICROSOFT_CLIENT_ID"],
    help: "Azure app client id for Outlook OAuth.",
  },
  {
    slug: "ms_oauth_secret",
    category: "Communication",
    label: "Microsoft OAuth Client Secret",
    emoji: "🔐",
    envVars: ["MICROSOFT_CLIENT_SECRET"],
    help: "Azure app client secret for Outlook OAuth.",
  },
  {
    slug: "meta_app_id",
    category: "Social",
    label: "Meta App ID",
    emoji: "📘",
    envVars: ["META_APP_ID"],
    help: "Meta developer app id for Instagram Graph API.",
  },
  {
    slug: "meta_app_secret",
    category: "Social",
    label: "Meta App Secret",
    emoji: "📘",
    envVars: ["META_APP_SECRET"],
    help: "Meta developer app secret for Instagram Graph API.",
  },
  {
    slug: "gologin",
    category: "Social",
    label: "GoLogin API Token",
    emoji: "🌐",
    envVars: ["GOLOGIN_API_TOKEN"],
    help: "Browser profile manager for stealth browsing.",
    href: "https://app.gologin.com/personalArea/Settings/api",
  },
  {
    slug: "late",
    category: "Social",
    label: "LATE Cross-Post API",
    emoji: "📤",
    envVars: ["LATE_API_KEY"],
    help: "Cross-posting service.",
  },
  {
    slug: "vps_url",
    category: "Infrastructure",
    label: "Production VPS URL",
    emoji: "🖥️",
    envVars: ["VPS_URL", "RECORDING_SERVER_URL"],
    help: "Where the dashboard talks to VNC + Chrome service.",
    placeholder: "https://srv1197943.taild42583.ts.net:10000",
  },
  {
    slug: "vnc_key",
    category: "Infrastructure",
    label: "VNC Manager API Key",
    emoji: "🔒",
    envVars: ["VNC_API_KEY"],
    help: "Auth secret for the VNC manager service.",
  },
  {
    slug: "vnc_url",
    category: "Infrastructure",
    label: "VNC Manager URL",
    emoji: "🌐",
    envVars: ["VNC_MANAGER_URL"],
    help: "VNC manager endpoint.",
  },
  {
    slug: "memory_vault_url",
    category: "Infrastructure",
    label: "Memory Vault URL",
    emoji: "🗂️",
    envVars: ["MEMORY_VAULT_API_URL"],
    help: "File-tree memory API endpoint.",
  },
  {
    slug: "memory_vault_token",
    category: "Infrastructure",
    label: "Memory Vault Token",
    emoji: "🔐",
    envVars: ["MEMORY_VAULT_TOKEN"],
    help: "Auth token for the file-tree memory API.",
  },
  {
    slug: "claude_bridge_url",
    category: "Infrastructure",
    label: "Claude Bridge URL",
    emoji: "🌉",
    envVars: ["CLAUDE_BRIDGE_URL"],
    help: "Local Claude Bridge endpoint.",
  },
  {
    slug: "claude_bridge_key",
    category: "Infrastructure",
    label: "Claude Bridge Key",
    emoji: "🔑",
    envVars: ["CLAUDE_BRIDGE_KEY"],
    help: "Auth key for the local Claude Bridge.",
  },
  {
    slug: "project_doc_id",
    category: "Workflow & Storage",
    label: "Project Google Doc ID",
    emoji: "📝",
    envVars: ["PROJECT_DOC_ID"],
    help: "Doc id where project decisions get appended.",
  },
  {
    slug: "github_pat",
    category: "Workflow & Storage",
    label: "GitHub PAT",
    emoji: "🐙",
    envVars: ["GITHUB_PAT"],
    help: "Read-only GitHub token for the Project Tree tab. Fine-grained, scoped to your dashboard repo.",
    href: "https://github.com/settings/tokens?type=beta",
    placeholder: "github_pat_…",
    testable: true,
  },
  {
    slug: "vercel_token",
    category: "Infrastructure",
    label: "Vercel Token",
    emoji: "▲",
    envVars: ["VERCEL_TOKEN"],
    help: "Vercel API token for deployment automation.",
    href: "https://vercel.com/account/tokens",
    placeholder: "Paste your Vercel token",
    testable: true,
  },
  {
    slug: "inngest_event",
    category: "Infrastructure",
    label: "Inngest Event Key",
    emoji: "📨",
    envVars: ["INNGEST_EVENT_KEY"],
    help: "Used by the Agent Workflows runtime to publish events.",
    href: "https://app.inngest.com/env/production/manage/keys",
  },
  {
    slug: "inngest_signing",
    category: "Infrastructure",
    label: "Inngest Signing Key",
    emoji: "✍️",
    envVars: ["INNGEST_SIGNING_KEY"],
    help: "Validates incoming Inngest webhook signatures.",
    href: "https://app.inngest.com/env/production/manage/signing-key",
  },
  {
    slug: "agent_runner_url",
    category: "Infrastructure",
    label: "Agent Runner URL",
    emoji: "🤖",
    envVars: ["AGENT_RUNNER_URL"],
    help: "Endpoint for the VPS agent-runner service that spawns Claude subagents.",
    placeholder: "https://srv1197943.taild42583.ts.net:.../agent-runner",
  },
  {
    slug: "agent_runner_token",
    category: "Infrastructure",
    label: "Agent Runner Token",
    emoji: "🔐",
    envVars: ["AGENT_RUNNER_TOKEN"],
    help: "Auth token for the agent-runner service.",
  },
  {
    slug: "terminal_runner_url",
    category: "Infrastructure",
    label: "Terminal Runner URL",
    emoji: "🖥️",
    envVars: ["TERMINAL_RUNNER_URL"],
    help: "Endpoint for the VPS terminal-server that spawns persistent tmux sessions for /agency/terminals. Must be HTTPS and reachable from the browser (Tailscale Funnel).",
    placeholder: "https://srv1197943.taild42583.ts.net:.../terminals",
  },
  {
    slug: "terminal_runner_token",
    category: "Infrastructure",
    label: "Terminal Runner Token",
    emoji: "🔐",
    envVars: ["TERMINAL_RUNNER_TOKEN"],
    help: "Bearer token for the terminal-server. Generate any 32+ char random string.",
  },
  // ── MCP stack — added by scripts/install-mcps.sh ──
  {
    slug: "playwright_mcp_token",
    category: "Infrastructure",
    label: "Playwright MCP Token",
    emoji: "🎭",
    envVars: ["PLAYWRIGHT_MCP_TOKEN"],
    help: "Bearer token for the Playwright MCP container on srv1197943. Auto-generated by install-mcps.sh; rotate by deleting the row + re-running.",
  },
  {
    slug: "devtools_mcp_token",
    category: "Infrastructure",
    label: "Chrome DevTools MCP Token",
    emoji: "🔍",
    envVars: ["DEVTOOLS_MCP_TOKEN"],
    help: "Bearer token for the Chrome DevTools MCP. Used to read browser console / network / performance via the existing CDP on the VPS.",
  },
  {
    slug: "postgres_mcp_token",
    category: "Infrastructure",
    label: "Postgres MCP Token",
    emoji: "🐘",
    envVars: ["POSTGRES_MCP_TOKEN"],
    help: "Bearer token for the Postgres MCP. Wraps a direct connection to Supabase Postgres so agents can run DDL + complex queries.",
  },
  {
    slug: "postgres_connection_string",
    category: "Infrastructure",
    label: "Postgres Connection String",
    emoji: "🔌",
    envVars: ["POSTGRES_CONNECTION_STRING"],
    help: "Supabase Pooler URL (Transaction mode, port 6543). Pull from Project Settings → Database → Connection string. Powers the Postgres MCP.",
    placeholder: "postgresql://postgres.<ref>:<password>@aws-0-<region>.pooler.supabase.com:6543/postgres",
  },
  {
    slug: "github_mcp_token",
    category: "Infrastructure",
    label: "GitHub MCP Token",
    emoji: "🐙",
    envVars: ["GITHUB_MCP_TOKEN"],
    help: "OAuth access token for the GitHub MCP. Auto-populated by /api/mcp/oauth/github/callback after the user clicks Connect on /jarvis/mcps; rotate by re-running the OAuth flow.",
  },
  {
    slug: "github_mcp_oauth_client_id",
    category: "Infrastructure",
    label: "GitHub MCP OAuth Client ID",
    emoji: "🆔",
    envVars: ["GITHUB_MCP_OAUTH_CLIENT_ID"],
    help: "OAuth App client ID for the GitHub MCP install flow (PKCE — no client secret needed). Create the OAuth app at https://github.com/settings/developers with callback URL https://outreach-github.vercel.app/api/mcp/oauth/github/callback.",
  },
  {
    slug: "context7_api_key",
    category: "AI / LLM",
    label: "Context7 API Key",
    emoji: "📚",
    envVars: ["CONTEXT7_API_KEY"],
    help: "API key for context7.com — up-to-date library docs MCP. Free tier exists. Lets agents read current Next.js/Supabase/etc. docs instead of hallucinating from training data.",
  },
  {
    slug: "brave_search_api_key",
    category: "Search & Scraping",
    label: "Brave Search API Key",
    emoji: "🦁",
    envVars: ["BRAVE_SEARCH_API_KEY"],
    help: "Brave Search API key — backs the Brave Search MCP. Free tier (2k queries/mo). Used by agents for web research.",
  },
  {
    slug: "sentry_dsn",
    category: "Infrastructure",
    label: "Sentry DSN",
    emoji: "🪺",
    envVars: ["SENTRY_DSN", "NEXT_PUBLIC_SENTRY_DSN"],
    help: "Sentry project DSN — already used by @sentry/nextjs in production. The Sentry MCP also reads this to scope queries.",
    placeholder: "https://...@o....ingest.sentry.io/...",
  },
  {
    slug: "sentry_auth_token",
    category: "Infrastructure",
    label: "Sentry Auth Token",
    emoji: "🔑",
    envVars: ["SENTRY_AUTH_TOKEN"],
    help: "Personal/team auth token for the Sentry API. Lets the Sentry MCP read errors + breadcrumbs without re-running device-code OAuth on every fresh session.",
  },
  {
    slug: "twilio_account_sid",
    category: "Communication",
    label: "Twilio Account SID",
    emoji: "📞",
    envVars: ["TWILIO_ACCOUNT_SID"],
    help: "Twilio Account SID. Pairs with TWILIO_AUTH_TOKEN for the Twilio MCP (alpha as of Apr 2026 — fall back to GHL if flaky).",
  },
  {
    slug: "twilio_auth_token",
    category: "Communication",
    label: "Twilio Auth Token",
    emoji: "🔐",
    envVars: ["TWILIO_AUTH_TOKEN"],
    help: "Twilio Auth Token (paired with TWILIO_ACCOUNT_SID). Powers the Twilio MCP for SMS sends + reply detection.",
  },
  {
    slug: "custom",
    category: "Other",
    label: "Custom (type your own env var name)",
    emoji: "🛠️",
    envVars: [],
    help: "Free-form. Type the env-var name and paste the value.",
  },
]

/** Bootstrap-only secrets — never UI-managed; getSecret returns env-only. */
export const BOOTSTRAP_ENV_VARS = new Set<string>([
  "NEXT_PUBLIC_SUPABASE_URL",
  "NEXT_PUBLIC_SUPABASE_ANON_KEY",
  "SUPABASE_SERVICE_ROLE_KEY",
  "ADMIN_PIN",
  "SESSION_SIGNING_SECRET",
  "CRON_SECRET",
  "OUTREACH_MEMORY_MCP_KEY",
])

export function findProviderBySlug(slug: string): ProviderEntry | null {
  return PROVIDERS.find((p) => p.slug === slug) ?? null
}

export function findProviderByEnvVar(envVar: string): ProviderEntry | null {
  return (
    PROVIDERS.find((p) => p.envVars.includes(envVar)) ?? null
  )
}

/** Mask all but the last 4 chars. Empty / very short values get a flat dot. */
export function maskSecret(raw: string | null | undefined): string {
  if (!raw) return ""
  const s = String(raw)
  if (s.length <= 4) return "•••••"
  return `${s.slice(0, 3)}…${s.slice(-4)}`
}
