// POST /api/runs/[id]/summarize — manual trigger of the summary generator.
// Normally summaries are generated by the summarizeRun Inngest function fired
// at run completion; this endpoint lets the user re-summarize on demand.

import { NextRequest, NextResponse } from "next/server"
import { inngest } from "@/lib/inngest/client"

export const dynamic = "force-dynamic"
export const runtime = "nodejs"

type Ctx = { params: Promise<{ id: string }> }

export async function POST(_req: NextRequest, { params }: Ctx) {
  const { id } = await params
  await inngest.send({
    name: "workflow/run.summarize",
    data: { run_id: id, force: true },
  })
  return NextResponse.json({ ok: true, queued: true })
}
