/**
 * GET /api/content/batch/status?id=<batch_id>
 * Returns the current status and progress of a batch job.
 * Also returns all content pieces generated by this batch.
 */

import { NextRequest, NextResponse } from 'next/server'
import { createClient } from '@supabase/supabase-js'

export const dynamic = 'force-dynamic'

const supabase = createClient(
  process.env.NEXT_PUBLIC_SUPABASE_URL!,
  process.env.SUPABASE_SERVICE_ROLE_KEY || process.env.NEXT_PUBLIC_SUPABASE_ANON_KEY!
)

export async function GET(req: NextRequest) {
  try {
    const { searchParams } = req.nextUrl
    const id = searchParams.get('id')

    if (!id) {
      return NextResponse.json({ error: 'Batch ID required' }, { status: 400 })
    }

    // Get batch info
    const { data: batch, error: batchErr } = await supabase
      .from('content_batches')
      .select('*')
      .eq('id', id)
      .single()

    if (batchErr || !batch) {
      return NextResponse.json({ error: 'Batch not found' }, { status: 404 })
    }

    // Get generated pieces
    const { data: pieces, error: piecesErr } = await supabase
      .from('content_pieces')
      .select('*')
      .eq('batch_id', id)
      .order('scheduled_date', { ascending: true })

    return NextResponse.json({
      batch,
      pieces: pieces || [],
      summary: {
        total: batch.total_pieces,
        completed: batch.completed_pieces,
        status: batch.status,
        progress: batch.progress,
        formats: (pieces || []).reduce((acc: Record<string, number>, p: any) => {
          acc[p.format] = (acc[p.format] || 0) + 1
          return acc
        }, {}),
      },
    })
  } catch (e: any) {
    return NextResponse.json({ error: e.message }, { status: 500 })
  }
}
