/**
 * Canonical list of variables available to automation steps.
 *
 * When Dylan types `{{` in a step value field, the autocomplete
 * dropdown surfaces these tokens. The runtime replay engine on the
 * VPS substitutes `{{token}}` (or `{token}`) with the lead's actual
 * data before clicking / typing.
 *
 * Keep in sync with whatever shape the /replay endpoint accepts in
 * its `variables` map. The catalog is intentionally a SUPERSET of
 * what's used today so we can document where each token comes from.
 *
 * If you add a variable here, also list it in the autocomplete UI's
 * filter logic — every entry is rendered without further code
 * changes thanks to the catalog-driven approach.
 */

export interface AutomationVariable {
  /** Machine name, e.g. "username". Inserted as `{{username}}`. */
  name: string
  /** Short label for the dropdown row. */
  label: string
  /** One-line hint explaining what this token resolves to at runtime. */
  hint: string
  /** Sample value so the user can preview what gets inserted. */
  sample?: string
  /** Grouping for sectioned dropdowns later. */
  group?: "lead" | "message" | "account" | "system"
}

export const AUTOMATION_VARIABLES: AutomationVariable[] = [
  // ── Lead identity ──
  {
    name: "username",
    label: "Username",
    hint: "Lead's platform handle (no @)",
    sample: "morganpilates",
    group: "lead",
  },
  {
    name: "first_name",
    label: "First name",
    hint: "Lead's first name",
    sample: "Alex",
    group: "lead",
  },
  {
    name: "last_name",
    label: "Last name",
    hint: "Lead's last name",
    sample: "Morgan",
    group: "lead",
  },
  {
    name: "full_name",
    label: "Full name",
    hint: "First + last name",
    sample: "Alex Morgan",
    group: "lead",
  },
  {
    name: "company",
    label: "Company",
    hint: "Lead's business / brand name",
    sample: "Morgan Pilates",
    group: "lead",
  },
  {
    name: "business_niche",
    label: "Niche",
    hint: "Lead's industry or category",
    sample: "Pilates studio",
    group: "lead",
  },
  {
    name: "city",
    label: "City",
    hint: "Lead's city",
    sample: "Austin",
    group: "lead",
  },
  {
    name: "follower_count",
    label: "Followers",
    hint: "Lead's follower count (number)",
    sample: "12400",
    group: "lead",
  },
  {
    name: "bio",
    label: "Bio",
    hint: "Scraped profile bio text",
    sample: "Yoga + Pilates coach",
    group: "lead",
  },

  // ── Targeting ──
  {
    name: "target_url",
    label: "Profile URL",
    hint: "Full URL to the lead's profile page",
    sample: "https://instagram.com/morganpilates",
    group: "lead",
  },
  {
    name: "target_handle",
    label: "Target handle",
    hint: "Platform username with @",
    sample: "@morganpilates",
    group: "lead",
  },

  // ── Message body ──
  {
    name: "message",
    label: "Message",
    hint: "Personalized message text generated by AI",
    sample: "Hey! Love what you do…",
    group: "message",
  },
  {
    name: "subject",
    label: "Subject",
    hint: "Email subject line (only used for email steps)",
    sample: "Quick question, Alex",
    group: "message",
  },

  // ── Account context ──
  {
    name: "account_username",
    label: "Sender handle",
    hint: "The account doing the sending",
    sample: "@dcmarketing",
    group: "account",
  },
]

/**
 * Look up a variable by name. Returns undefined for unknown tokens —
 * useful for runtime validation in the replay engine.
 */
export function findAutomationVariable(
  name: string
): AutomationVariable | undefined {
  return AUTOMATION_VARIABLES.find((v) => v.name === name)
}

/**
 * Filter variables by case-insensitive substring against name + label.
 * Used by the autocomplete component when the user keeps typing after
 * `{{`.
 */
export function filterAutomationVariables(
  query: string,
  catalog: AutomationVariable[] = AUTOMATION_VARIABLES
): AutomationVariable[] {
  const q = query.trim().toLowerCase()
  if (!q) return catalog
  return catalog.filter(
    (v) =>
      v.name.toLowerCase().includes(q) ||
      v.label.toLowerCase().includes(q)
  )
}
